### ISSUE TITLE
Uncaught ReferenceError: QzoneApp is not defined

### ISSUE THREAD

**Issue by feix760** [BetterJS/badjs-report#15]
设备：android QQ5.5~5.7
原因：下载进度事件会调用QzoneApp.fire()
解决办法：没很好的办法，在window上挂一个空的QzoneApp
window.QzoneApp = {
   fire: function() {}
}

**Comment by adamchuan** [comment]
学习了

**Comment by yorts52** [comment]
这类问题更通用的解决方案是:
1. 设置 ignore, 配置默认支持;
2. 从根本上解决这个问题推动手 Q 团队调整事件的处理方式, 通过 dispatchEvent 来做, 业务侧如果不关注该事件不做监听就可以.
