### ISSUE TITLE
imprt tryJs undefined

### ISSUE THREAD

**Issue by liyatang** [BetterJS/badjs-report#17]
```javascript
import badjs from 'badjs-report';

badjs.init({...}).tryJs(); // 提示 tryJs 不是一个function
```

通过import方式不能使用tryJs，因为 bj-wrap.js 源码内并没有做相应的模块化处理。 而是简单的复制给 root.BJ_REPORT.tryJS

**Comment by yorts52** [comment]
1. https://github.com/BetterJS/badjs-report/blob/master/src/bj-report.js 是上报的基础部分（必选）
2. https://github.com/BetterJS/badjs-report/blob/master/src/bj-wrap.js 是上报的扩展部分（可选）
> 只有 2 里面才有 tryJs
如果要在项目中使用 tryJs 应该直接引用这个 https://github.com/BetterJS/badjs-report/blob/master/dist/bj-report-tryjs.min.js （包含 bj-report 和 bj-wrap）

**Comment by yorts52** [comment]
另外说一句 npm 上的版本比较旧了，@caihuiji 快来升级了

**Comment by liyatang** [comment]
谢谢，果然是npm上的版本太旧了。   @caihuiji 快升级

**Comment by caihuiji** [comment]
npm 上已经更新。  目前是1.2.2 版本
