### ISSUE TITLE
单页面应用的 from 应该取发生错误时的 location.href, 而不是init时的 location.href

### ISSUE THREAD

**Issue by Treri** [BetterJS/badjs-report#19]
单页面应用的情况下, init的 location.href 一般都不会是 发生错误时的 location.href.

所以获取 location.href的动作时, 应该是和获取错误 msg 在同一时间

**Comment by caihuiji** [comment]
这个建议不错。 我们后面优化一下

**Comment by yorts52** [comment]
已处理~

https://github.com/BetterJS/badjs-report/commit/7ccd6eb599f6bac5f50a4e886e31cab6e126ac3a

https://github.com/BetterJS/badjs-acceptor/commit/f0d62cd77d42d60baabd958f3e5f13f4cd4d7f19
