### ISSUE TITLE
BJ_REPORT.tryJs().spyCustom( 

### ISSUE THREAD

**Issue by Beven91** [BetterJS/badjs-report#21]
BJ_REPORT.tryJs().spyCustom((customFunction)

有时候需要吧customFunction的静态属性也复制一下，不然会影响原始customFunction的使用

**Comment by caihuiji** [comment]
customFunction 需要挂载静态变量吗？
需要实例化的 customFunction  才需要挂载静态变量吧， 能否给一下你的场景
