### ISSUE TITLE
Cannot GET /badjs

### ISSUE THREAD

**Issue by jwzhangjie** [BetterJS/badjs-report#24]
搭建好之后，上报出现Cannot GET /badjs

**Comment by caihuiji** [comment]
是不是没有指定 上报的URL 地址？

**Comment by shirleyxyli** [comment]
请问在哪里指定上报URL地址的喔

**Comment by loskael** [comment]
`BJ_REPORT.init` 的时候指定

**Comment by PLQin** [comment]
指定地址为: `http://127.0.0.1:8081/badjs` 或 `http://127.0.0.1:8083/badjs` 或 ``http://127.0.0.1/badjs` 提示 `Cannot GET /badjs` ;  

这个 `badjs` 的路径在哪里配置 ?
