### ISSUE TITLE
请问1.3版本什么时候发布？

### ISSUE THREAD

**Issue by ThinkRealize** [BetterJS/badjs-report#26]
是的 packjson.json version 版本没有改？
用1.2.3 版本，BJ_REPORT 对象只有以下方法
debug: function (e){}
info: function (e){}
init: function (e){}
push: function (e){}
report: function (e){}
tryJs: function (e){}

没和离线日志有关的方法。

**Comment by caihuiji** [comment]
还没有正式发布到npm ，还在内测阶段

**Comment by ThinkRealize** [comment]
好吧，谢谢。那我关闭了。
