### ISSUE TITLE
请求的返回应该怎么写？

### ISSUE THREAD

**Issue by thomasyxy** [BetterJS/badjs-report#27]
如果返回一个json格式，会提示格式错误，不返回的话又报404，虽然不影响功能，但是是否避免这些报错信息？

**Comment by yorts52** [comment]
你是说上报接口应该返回什么？
直接响应 204（No Content） 就好了

**Comment by caihuiji** [comment]
前端是采用 image 上报的， 已经默认204。 为什么需要返回json
