### ISSUE TITLE
监控系统不能查看到历史日志和实时日志，统计日志显示正常统计

### ISSUE THREAD

**Issue by Time-merchant** [BetterJS/badjs-report#29]
拷贝下载的bj-report.js到工程，随后使用如下方法进行初始化

```js
BJ_REPORT.init({
    id: 5,                                // 上报 id, 不指定 id 将不上报
    uin: 1233434,                             // 指定用户 id, (默认已经读取 qq uin)
    delay: 1000,                          // 当 combo 为 true 可用，延迟多少毫秒，合并缓冲区中的上报（默认）
    url: "//**域名**/badjs",         // 指定上报地址
    // ignore: [/Script error/i],            // 忽略某个错误
    random: 1,                            // 抽样上报，1~0 之间数值，1为100%上报（默认 1）
    // repeat: 5,                            // 重复上报次数(对于同一个错误超过多少次不上报)
                                          // 避免出现单个用户同一错误上报过多的情况
    // onReport: function(id, errObj){},     // 当上报的时候回调。 id: 上报的 id, errObj: 错误的对象
    // submit,                               // 覆盖原来的上报方式，可以自行修改为 post 上报等
    ext: {},                               // 扩展属性，后端做扩展处理属性。例如：存在 msid 就会分发到 monitor,
    offlineLog : false,                    // 是否启离线日志 [默认 true]
    offlineLogExp : 5                // 离线有效时间，默认最近5天
  });
```

可以看到 http://**域名**/badjs 接口进行正常的上报，而接口 http://**域名**/offlineAuto 则报错，浏览器显示状态为404，查看服务器日志返回为403.

登录监控系统可以查看统计面板中的数据，历史日志和实时日志面板中均没有正常返回日志记录。

请问出现这些问题的原因是什么？

**Comment by yorts52** [comment]
@caihuiji  离线日志的问题，你看看

**Comment by caihuiji** [comment]
1. http://域名/offlineAuto 请求失败的
麻烦看一下 badjs-acceptor/app.js ，里面是否有offlineAuto ，如果没有 ，请更一下一下服务器的代码。
如果有，看看nginx 之类配置转发有问题，
2. 历史日志查询没有日志，但是统计数据有日志
麻烦先看看 debug 启动， 看看请求是不是已经正常写入mongodb， 怀疑中间某一部转发时候有问题

**Comment by Time-merchant** [comment]
@chyingp 
1、更新了代码后app.js里有offlineAuto。然后发现offlineAuto接口还是一样的错404
2、历史日志可以查询到上报的数据，但是统计的数据都没有了，实时监控的websocket报错： Error during WebSocket handshake: Unexpected response code: 404

运维使用docker部署，Nginx80端口已被占用，用其他端口进行转发了，这样是否有问题

**Comment by yorts52** [comment]
404 很可能是转发出错了，你看看 nginx 配置是否有问题

> 另外，@chyingp 无辜躺枪，哈哈

**Comment by caihuiji** [comment]
docker 代码确实有点旧了。 我最近更新一下。
nginx 也需要配置一下 websocket 转发

**Comment by Time-merchant** [comment]
🤦‍♀️ @错人啦，sorry~。今天我们重新在一个服务器上部署了，目前历史日志和实时监控模块都可以工作，目测统计日志应该也可以（一定是零点统计的是吧？）。offlineAuto接口还是404错误，申请的时候业务网站填了 *.qq.com这种格式也不行。请问offlineAuto这个接口的作用是什么，会影响功能吗？

**Comment by Time-merchant** [comment]
@yorts52 请问日志统计的我们查看了mongodb，历史日志记录有，但是MySQL没有从mongodb拉到统计日志。是哪里有问题？

**Comment by yorts52** [comment]
说明一下，统计的结果是有延迟的，另外，可以从几方面定位：

1、检查【badjs-storage】 https://github.com/BetterJS/badjs-storage/blob/7235786d444c50582b9954c8c57bf7db5893cb14/service/realTotal.js 的统计是否正常

2、检查【badjs-storage】 https://github.com/BetterJS/badjs-storage/blob/7235786d444c50582b9954c8c57bf7db5893cb14/service/query.js 的查询服务是否正常

3、检查【badjs-web】https://github.com/BetterJS/badjs-web/blob/master/service/StatisticsService.js#L109 的统计服务是否正常, 且结果写入 [mysql](https://github.com/BetterJS/badjs-web/blob/master/project.json#L5) 是否正常
