### ISSUE TITLE
上报的堆栈信息被截断，起码能不能自己配置最长上报信息的长度？

### ISSUE THREAD

**Issue by AminHuang** [BetterJS/badjs-report#32]
RT

**Comment by yorts52** [comment]
GET 请求内容长度会有限制，如果内容过长可以使用 POST 上报

**Comment by yorts52** [comment]
@caihuiji  这里为什么要做截断 https://github.com/BetterJS/badjs-report/blob/0193a3ffc1fdba292c2367015dba051f8ab77702/src/bj-report.js#L355

**Comment by caihuiji** [comment]
之前存在一种情况是某个错误的msg 长，造成整个上报失败。
通过评估发现这个错误是不合理的错误，
正常的错误msg 是不会超过500 ， 超过是属于不合理的， 所以左右有效截断。
@AminHuang  你的错误信息能给我们看看，我们重新评估一下。
