### ISSUE TITLE
代码比较奇怪的几点

### ISSUE THREAD

**Issue by WebGuHui** [BetterJS/badjs-report#33]
1、
![image](https://user-images.githubusercontent.com/11729740/29518591-8c87c19a-86ac-11e7-948a-f39626a0503e.png)
不是很明白为什么我自己提交，你要给我一个GET的 url，我还需要自己拆吗？

2、
![image](https://user-images.githubusercontent.com/11729740/29518652-d354c154-86ac-11e7-8fcd-beca150d270c.png)

![image](https://user-images.githubusercontent.com/11729740/29518725-1233d4e6-86ad-11e7-873a-71e6c52916fc.png)

![image](https://user-images.githubusercontent.com/11729740/29518739-1cf9c444-86ad-11e7-87cb-2d3f5e987dd3.png)

为什么同一个error，会被processError给解析一遍，然后触发两次onReport？

**Comment by WebGuHui** [comment]
请问什么情况了

**Comment by huangjiaxing** [comment]
我也有这个问题，同一个错误会上报两次，是出于什么考虑

**Comment by librajt** [comment]
get请求主要为了使用gif图打点的方式方便上报。
被处理两遍，可能是为了上报 stack 之类的信息，所以分开成两条。但判断条件好像不完善。
纯猜测

**Comment by yorts52** [comment]
@WebGuHui 

1、问题 1 已经更新，参考 https://github.com/BetterJS/badjs-report/commit/7f3737f81b4a5d6c1c5f3603b74c493b73cc3813

@WebGuHui @huangjiaxing @librajt 
2、报两次的问题参考 https://github.com/BetterJS/badjs-report/blob/7f3737f81b4a5d6c1c5f3603b74c493b73cc3813/src/bj-report.js#L20 和 https://github.com/BetterJS/badjs-report/blob/7f3737f81b4a5d6c1c5f3603b74c493b73cc3813/src/bj-report.js#L409-L411
这两次的日志包含的内容基本一致，区别是 msg 和 level，其中 level = 2 的日志是不入库的，可以从实时日志里面找到，而入库的信息里保留原来的 Error.stack 是必要的，事实上，这部分的处理交给服务器来做也是可以的，另外，这部分是 @caihuiji 加的，@caihuiji 来解释一下？

**Comment by keminu** [comment]
上报两次的问题有解决方式吗？
