### ISSUE TITLE
_submit_log无法执行

### ISSUE THREAD

**Issue by letmeknowhow** [BetterJS/badjs-report#34]
当第一个log为offlinelog时，_log_list会被清空之后执行_submit_log，函数在comboTimeout被重置前返回，导致comboTimeout永远为true，_submit_log不会再执行。

**Comment by librajt** [comment]
不止是这种情况，代理过 onerror 后，先 push 再 _process_log，会连续触发两次 _submit_log，第一次是 timeout 触发的，紧接着被第二次 clearTimeout 了，但 comboTimeout 非0，同样导致 _submit_log 不会再执行。

**Comment by yorts52** [comment]
问题由这次调整引入 https://github.com/BetterJS/badjs-report/commit/2adfcea3a48fbf4140a4d59f3fba9bef52f06233
