### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by haledeng** [BetterJS/badjs-report#4]
我发现 bj-report 在上报的时候，有循环引用的错误。

value = JSON.stringify(value);
[http://stackoverflow.com/questions/22806305/window-onerror-and-object-event](http://stackoverflow.com/questions/22806305/window-onerror-and-object-event)

![cb45c67f-19ac-48ba-a175-3b93faf3dd57](https://cloud.githubusercontent.com/assets/2292731/7827944/ad5def88-045f-11e5-9cbd-a14c7ba24095.png)
![d78936e0-d033-4a43-b83f-175ecacc4174](https://cloud.githubusercontent.com/assets/2292731/7827945/ad892ca2-045f-11e5-842a-b0ac0d1d5313.png)

**Comment by caihuiji** [comment]
以前的ERROR 对象是有上报的， 怀疑是这里面产生了循环引用，
所以我们对这个错误进行捕获和上报：
![28a7866c-ba70-4b1b-9b88-a676674ed2e9](https://cloud.githubusercontent.com/assets/2292731/7875888/9390e3d4-05f5-11e5-9ba3-a169098ea120.png)

但是我发现有新的错误上报上来了
![image](https://cloud.githubusercontent.com/assets/2292731/7875923/d3be18b4-05f5-11e5-9f08-509a6d0920c5.png)

所以我们再继续观察一段时间

**Comment by caihuiji** [comment]
[boject Event ]是某些andorid 手机浏览器里面抛出的，目前没有是什么原因造成的

**Comment by longyiyiyu** [comment]
我这边加了些逻辑，发现是script资源加载错误的时候会报[object Event]错误，它直接把error对象抛出来了
